2023-12-02 18:31:25.293767: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-02 18:31:25.359667: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-02 18:31:25.359696: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-02 18:31:25.360583: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-02 18:31:25.365300: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-02 18:31:31.279575: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1130, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/transformers/trainer.py", line 166, in <module>
    import datasets
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/datasets/__init__.py", line 22, in <module>
    from .arrow_dataset import Dataset
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 58, in <module>
    import pandas as pd
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/core/frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/core/generic.py", line 187, in <module>
    from pandas.core.window import (
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-x86_64-linux-gnu.so)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/new-stg/home/banghua/Amazon-Rating-Prediction/BERT_multigpu.py", line 10, in <module>
    from transformers import AutoModelForSequenceClassification, Trainer, TrainingArguments
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1120, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1132, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /new-stg/home/banghua/anaconda3/envs/LLM/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-x86_64-linux-gnu.so)
